// ─── UI Primitives — FounderCentral Design System ──────────────────
// Every primitive exports from this barrel. Pages import from here.

export { Avatar } from './Avatar'
export { Badge, investorTypeBadgeVariant, statusBadgeVariant } from './Badge'
export { Button } from './Button'
export { Chip } from './Chip'
export { DataTable } from './DataTable'
export { DeltaBadge } from './DeltaBadge'
export { Dialog } from './Dialog'
export { Drawer } from './Drawer'
export { EmptyState } from './EmptyState'
export { FilterPill } from './FilterPill'
export { HeroNumber } from './HeroNumber'
export { HeroSection } from './HeroSection'
export { IconButton } from './IconButton'
export { KPIGrid } from './KPIGrid'
export { KPICard } from './KPICard'
export { MatchRing } from './MatchRing'
export { PageHeader } from './PageHeader'
export { PillBarChart } from './PillBarChart'
export { PillTabs } from './PillTabs'
export { ProgressRing } from './ProgressRing'
export { SearchInput } from './SearchInput'
export { Select } from './Select'
export { SkeletonLoader } from './SkeletonLoader'
export { SkeletonBlock, SkeletonText, SkeletonCircle } from './Skeleton'
export { SmoothLineChart } from './SmoothLineChart'
export { Sparkline } from './Sparkline'
export { Stat } from './Stat'
export { Surface } from './Surface'
export { Tabs, TabsContent } from './Tabs'
export { TextField } from './TextField'
export { TextArea } from './TextArea'
